language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1
  - 7.2

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: false

before_install:
  - composer update --prefer-source

script: vendor/bin/phpunit tests