language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

sudo: false

before_install:
  - composer update --prefer-source

script: vendor/bin/phpunit tests
